config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/calculadora', to: 'calculator#math'
  get '/calculadora/:num1/:num2', to: 'calculator#math'

  get '/calculadora/:num1/:num2/sum', to: 'calculator#sum', as: "sum"
  get '/calculadora/:num1/:num2/minus', to: 'calculator#minus', as: "minus"
  get '/calculadora/:num1/:num2/multiply', to: 'calculator#multiply', as: "multiply"
  get '/calculadora/:num1/:num2/division', to: 'calculator#division', as:"division"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
        
    end
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
    def math
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
    end
    
    def sum
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
    end
    def minus
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
    end
    def multiply
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
    end
    def division
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
    end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
    def now
    end
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculator/division.html.erb
<h1>Divisão</h1>
<%= @num1 / @num2 %>

app/views/calculator/math.html.erb
<h1>calculadora</h1>
<%= @num1 %>
<%= @num2 %>
<h1>Operações</h1>
<ul>
<li><%= link_to "Soma", sum_path %></li>
<li><%= link_to "Subtração", minus_path %></li>
<li><%= link_to "Multiplicar", multiply_path %></li>
<li><%= link_to "Divisão", division_path %></li>
</ul>

app/views/calculator/minus.html.erb
<h1>Minus</h1>
<%= @num1 - @num2 %>

app/views/calculator/multiply.html.erb
<h1>Multiplicação</h1>
<%= @num1 * @num2 %>

app/views/calculator/sum.html.erb
<h1>Soma</h1>
<%= @num1 + @num2 %>

app/views/food/now.html.erb
<h1>help</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/presentation/home.html.erb
<h1>Poggers</h1>